"""init

Revision ID: ac69b5332416
Revises: 
Create Date: 2025-05-14 00:37:26.134865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac69b5332416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_table('bot_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_bot_users_telegram_id'))
    )
    op.create_table('tg_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tg_accounts')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_tg_accounts_tg_user_id'))
    )
    op.create_table('account_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_account_id', sa.BigInteger(), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], name='fk_account_sessions_bot_user_id_bot_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tg_account_id'], ['tg_accounts.id'], name='fk_account_sessions_tg_account_id_tg_accounts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_sessions')),
    sa.UniqueConstraint('bot_user_id', 'tg_account_id', name='uq_account_sessions_bot_user_id_tg_account_id')
    )
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_chats_user_id_bot_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_chats_chat_id'))
    )
    op.create_table('dossiers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_dossiers_user_id_bot_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossiers'))
    )
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('context_source', sa.Text(), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_queries_user_id_bot_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries'))
    )
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('openai_key', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_settings_user_id_bot_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('statistics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_statistics_user_id_bot_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics'))
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='fk_messages_chat_id_chats', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], name='fk_messages_user_id_bot_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('statistics')
    op.drop_table('settings')
    op.drop_table('queries')
    op.drop_table('dossiers')
    op.drop_table('chats')
    op.drop_table('account_sessions')
    op.drop_table('tg_accounts')
    op.drop_table('bot_users')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
