"""upd1

Revision ID: f24db805f079
Revises: 50115eb79c34
Create Date: 2025-05-11 01:17:25.065203

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f24db805f079'
down_revision: Union[str, None] = '50115eb79c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
